# load_averaged_tidy_data.R
#
#  This script allows project reviewers to load and examine
#  the independent tidy data set generated by the
#  run_analysis.R script.

df.tidy.data <- read.table(file = 'HAR_mean_and_std_variables_averaged_by_subject_and_activity.txt',
                          header = TRUE,
                          check.names = FALSE,
                          stringsAsFactors = FALSE)
View(df.tidy.data)
